import React from 'react'
import InfiniteCarousel from 'react-leaf-carousel';

export default function test() {
    return (
        <div>
            <InfiniteCarousel
    breakpoints={[
      {
        breakpoint: 500,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 2,
        },
      },
      {
        breakpoint: 768,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 3,
        },
      },
    ]}
    dots={true}
    showSides={true}
    sidesOpacity={.5}
    sideSize={.1}
    slidesToScroll={4}
    slidesToShow={4}
    scrollOnDevice={true}
  >
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
    <div>
      <img
        alt=''
        src='https://via.placeholder.com/150'
      />
    </div>
  </InfiniteCarousel>
        </div>
    )
}
